### ISSUE TITLE
mx_get_accounts doesn't pull insurance accounts from institution

### ISSUE THREAD

**Issue by yazmnh87** [mxenabled/mx-atrium-node#46]
When a customer links a bank that also has insurance through that institution, the insurance account information is not being returned.  

ie customer is banking though USAA and also has auto insurance.  mx is not returning the insurance account information from USAA, only the checking and savings account info.  The other accounts are useful.

**Comment by brettmortensen** [comment]
@yazmnh87 Thanks for reaching out.

Our team would be happy to dive in on this issue. Due to the nature of aggregation, we generally need more information. We use the https://atriumsupport.zendesk.com platform to gather information and correspond on these type of issues. Please login via that platform, create a ticket, and our team will investigate asap.
