### ISSUE TITLE
Is this library current with the most recent version of the MX API?

### ISSUE THREAD

**Issue by cthomaschase** [mxenabled/mx-atrium-node#51]
Hi, exploring the API - https://docs.mx.com/api#introduction

Is this library current with authentications methods, routes, etc?

Thanks.

**Comment by brettmortensen** [comment]
Hi @cthomaschase, thanks for reaching out.

Our "Atrium" libraries are not compatible with the "MX Platform API" you linked to above. Atrium is an older API that we still support, but we are no longer accepting new registrations. The MX Platform API is our latest API, but unfortunately we do not have any wrapper libraries at this time.

**Comment by marcus-ahle** [comment]
I wish I could sign up with Atrium.  I signed up recently and am trying to evaluate MX to compare against Finicity, Plaid, Yodlee, etc.. It's been completely awful so far. I have yet to make a successful API call to the development server. Every calls returns 500 Internal Server Error. Every. Single. Call... Support ticket has been opened for 4 days now and no ETA and just stating that "the engineers are looking into it ASAP". Is it returning 500 errors for every one? I can't possibly be the only person attempting to use the development server. Getting very close to giving up on MX completely because this is insane...

**Comment by corbt** [comment]
Any progress on this front? Would be awfully nice to have a nicely typed library wrapping the current API!

**Comment by brettmortensen** [comment]
Thanks for reaching out @corbt!

We are pursuing libraries for the MX Platform API, but do not have any timelines at the moment.

**Comment by marcus-ahle** [comment]
It would be nice if you could still allow people to sign up on Atrium until client libraries were available.
